// <auto-generated />
using System;
using DrugInventoryPro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrugInventoryPro.Migrations
{
    [DbContext(typeof(DrugInventoryContext))]
    [Migration("20260606084112_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrugInventoryPro.Models.Category", b =>
                {
                    b.Property<string>("Category_id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("category_id");

                    b.Property<string>("Category_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Related_disease")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("related_disease");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Category_id");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("DrugInventoryPro.Models.Department", b =>
                {
                    b.Property<string>("Department_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Contact_firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Department_id");

                    b.ToTable("Departments", null, t =>
                        {
                            t.HasTrigger("trg_Departments_Update");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("DrugInventoryPro.Models.Dispense", b =>
                {
                    b.Property<string>("Dispense_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Department_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Dispense_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Dispense_id");

                    b.ToTable("Dispense", null, t =>
                        {
                            t.HasTrigger("trg_Dispense_Insert");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("DrugInventoryPro.Models.DispenseDetail", b =>
                {
                    b.Property<string>("Dispense_detail_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Dispense_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Medicine_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Medicine_id");

                    b.Property<int?>("Quantity_dispensed")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity_requested")
                        .HasColumnType("int");

                    b.HasKey("Dispense_detail_id");

                    b.HasIndex("Dispense_id");

                    b.HasIndex("Medicine_id");

                    b.ToTable("DispenseDetails", (string)null);
                });

            modelBuilder.Entity("DrugInventoryPro.Models.MedicineUnit", b =>
                {
                    b.Property<int>("Unit_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Unit_id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Group_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Unit_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Unit_id");

                    b.ToTable("MedicineUnits", (string)null);
                });

            modelBuilder.Entity("DrugInventoryPro.Models.Medicines", b =>
                {
                    b.Property<string>("Medicine_id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("medicine_id");

                    b.Property<string>("Account_Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Account_Type");

                    b.Property<string>("Category_id")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("Expired_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("expired_at");

                    b.Property<string>("Lot")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lot");

                    b.Property<string>("Medicine_name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("medicine_name");

                    b.Property<string>("Packing_Size")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Packing_Size");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<int?>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("Stock");

                    b.Property<int?>("Unit_id")
                        .HasColumnType("int")
                        .HasColumnName("Unit_id");

                    b.HasKey("Medicine_id");

                    b.HasIndex("Category_id");

                    b.HasIndex("Unit_id");

                    b.ToTable("Medicines", null, t =>
                        {
                            t.HasTrigger("trg_Medicines_Update");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("DrugInventoryPro.Models.PurchaseOrderDetail", b =>
                {
                    b.Property<string>("PODetailID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Medicine_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("POID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Unit_idPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PODetailID");

                    b.HasIndex("Medicine_id");

                    b.HasIndex("POID");

                    b.ToTable("PurchaseOrderDetail", (string)null);
                });

            modelBuilder.Entity("DrugInventoryPro.Models.PurchaseOrders", b =>
                {
                    b.Property<int>("POID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("poid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("POID"));

                    b.Property<string>("Medicine_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("medicine_id");

                    b.Property<DateTime?>("PODate")
                        .HasColumnType("datetime2")
                        .HasColumnName("podate");

                    b.Property<string>("PONumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ponumber");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("POID");

                    b.HasIndex("Medicine_id");

                    b.ToTable("PurchaseOrders", (string)null);
                });

            modelBuilder.Entity("DrugInventoryPro.Models.Receive", b =>
                {
                    b.Property<string>("Receive_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Invoice_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Po_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Receive_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Received_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Total_amount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Receive_id");

                    b.ToTable("Receives", null, t =>
                        {
                            t.HasTrigger("trg_Receive_Insert");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("DrugInventoryPro.Models.ReceiveDetail", b =>
                {
                    b.Property<string>("Receive_detail_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Expiry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lot_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medicine_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity_received")
                        .HasColumnType("int");

                    b.Property<string>("Receive_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Receive_detail_id");

                    b.HasIndex("Medicine_id");

                    b.HasIndex("Receive_id");

                    b.ToTable("ReceiveDetails", (string)null);
                });

            modelBuilder.Entity("DrugInventoryPro.Models.Stock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockId"));

                    b.Property<string>("Medicine_id")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("medicine_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("StockId");

                    b.HasIndex("Medicine_id");

                    b.ToTable("Stock", (string)null);
                });

            modelBuilder.Entity("DrugInventoryPro.Models.User", b =>
                {
                    b.Property<string>("User_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Department_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Em")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_id");

                    b.HasIndex("Department_id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DrugInventoryPro.Models.DispenseDetail", b =>
                {
                    b.HasOne("DrugInventoryPro.Models.Dispense", "Dispense")
                        .WithMany("DispenseDetails")
                        .HasForeignKey("Dispense_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrugInventoryPro.Models.Medicines", "Medicine")
                        .WithMany()
                        .HasForeignKey("Medicine_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dispense");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("DrugInventoryPro.Models.Medicines", b =>
                {
                    b.HasOne("DrugInventoryPro.Models.Category", "Category")
                        .WithMany("Medicines")
                        .HasForeignKey("Category_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DrugInventoryPro.Models.MedicineUnit", "MedicineUnit")
                        .WithMany("Medicines")
                        .HasForeignKey("Unit_id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");

                    b.Navigation("MedicineUnit");
                });

            modelBuilder.Entity("DrugInventoryPro.Models.PurchaseOrderDetail", b =>
                {
                    b.HasOne("DrugInventoryPro.Models.Medicines", "Medicines")
                        .WithMany()
                        .HasForeignKey("Medicine_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DrugInventoryPro.Models.PurchaseOrders", "PurchaseOrder")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("POID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicines");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("DrugInventoryPro.Models.PurchaseOrders", b =>
                {
                    b.HasOne("DrugInventoryPro.Models.Medicines", "Medicines")
                        .WithMany()
                        .HasForeignKey("Medicine_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("DrugInventoryPro.Models.ReceiveDetail", b =>
                {
                    b.HasOne("DrugInventoryPro.Models.Medicines", "Medicines")
                        .WithMany()
                        .HasForeignKey("Medicine_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DrugInventoryPro.Models.Receive", "Receive")
                        .WithMany("ReceiveDetails")
                        .HasForeignKey("Receive_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Medicines");

                    b.Navigation("Receive");
                });

            modelBuilder.Entity("DrugInventoryPro.Models.Stock", b =>
                {
                    b.HasOne("DrugInventoryPro.Models.Medicines", "Medicines")
                        .WithMany()
                        .HasForeignKey("Medicine_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("DrugInventoryPro.Models.User", b =>
                {
                    b.HasOne("DrugInventoryPro.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("Department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DrugInventoryPro.Models.Category", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("DrugInventoryPro.Models.Dispense", b =>
                {
                    b.Navigation("DispenseDetails");
                });

            modelBuilder.Entity("DrugInventoryPro.Models.MedicineUnit", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("DrugInventoryPro.Models.PurchaseOrders", b =>
                {
                    b.Navigation("PurchaseOrderDetails");
                });

            modelBuilder.Entity("DrugInventoryPro.Models.Receive", b =>
                {
                    b.Navigation("ReceiveDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
